# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uia.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pa(object):
    def setupUi(self, pa):
        pa.setObjectName("pa")
        pa.resize(776, 483)
        self.CardWidget = CardWidget(pa)
        self.CardWidget.setGeometry(QtCore.QRect(520, 120, 231, 251))
        self.CardWidget.setObjectName("CardWidget")
        self.StrongBodyLabel = StrongBodyLabel(self.CardWidget)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(30, 20, 171, 171))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.EditableComboBox = EditableComboBox(pa)
        self.EditableComboBox.setGeometry(QtCore.QRect(340, 380, 121, 33))
        self.EditableComboBox.setObjectName("EditableComboBox")
        self.RadioButton = RadioButton(pa)
        self.RadioButton.setGeometry(QtCore.QRect(20, 440, 181, 24))
        self.RadioButton.setObjectName("RadioButton")
        self.PrimaryPushButton = PrimaryPushButton(pa)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(610, 430, 153, 41))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.StrongBodyLabel_2 = StrongBodyLabel(pa)
        self.StrongBodyLabel_2.setGeometry(QtCore.QRect(60, 380, 281, 31))
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.SubtitleLabel = SubtitleLabel(pa)
        self.SubtitleLabel.setGeometry(QtCore.QRect(20, 40, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.CardWidget_2 = CardWidget(pa)
        self.CardWidget_2.setGeometry(QtCore.QRect(120, 40, 421, 41))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.StrongBodyLabel_3 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(20, 10, 271, 19))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.label = QtWidgets.QLabel(pa)
        self.label.setGeometry(QtCore.QRect(50, 100, 431, 271))
        self.label.setStyleSheet("border-image: url(:/img/resource/img.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.HyperlinkButton = HyperlinkButton(pa)
        self.HyperlinkButton.setGeometry(QtCore.QRect(60, 290, 281, 71))
        self.HyperlinkButton.setObjectName("HyperlinkButton")

        self.retranslateUi(pa)
        QtCore.QMetaObject.connectSlotsByName(pa)

    def retranslateUi(self, pa):
        _translate = QtCore.QCoreApplication.translate
        pa.setWindowTitle(_translate("pa", "Form"))
        self.StrongBodyLabel.setText(_translate("pa", "<html><head/><body><p><span style=\" font-size:11pt;\">个人制作软件与mefrp</span></p><p><span style=\" font-size:11pt;\">（镜源映射）无关本</span></p><p><span style=\" font-size:11pt;\">软件只是为了方便使用</span></p><p><span style=\" font-size:11pt;\">mefrp（镜源映射）的</span></p><p><span style=\" font-size:11pt;\">         小伙伴们</span></p></body></html>"))
        self.RadioButton.setText(_translate("pa", "以其他系统的方式启动"))
        self.PrimaryPushButton.setText(_translate("pa", "启动服务"))
        self.StrongBodyLabel_2.setText(_translate("pa", "你的编号（简单启动后面那几个数字）："))
        self.SubtitleLabel.setText(_translate("pa", "简单启动"))
        self.StrongBodyLabel_3.setText(_translate("pa", "若出现无法连接服务器请转至高级启动"))
        self.HyperlinkButton.setText(_translate("pa", "联机快乐, MeFrp\n"
"哔哩哔哩 - 『千里之行，始于足下。』"))
from qfluentwidgets import CardWidget, EditableComboBox, HyperlinkButton, PrimaryPushButton, RadioButton, StrongBodyLabel, SubtitleLabel
import rc_rc
