# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uib.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pb(object):
    def setupUi(self, pb):
        pb.setObjectName("pb")
        pb.resize(775, 483)
        self.TextEdit = TextEdit(pb)
        self.TextEdit.setGeometry(QtCore.QRect(10, 100, 351, 371))
        self.TextEdit.setObjectName("TextEdit")
        self.SubtitleLabel = SubtitleLabel(pb)
        self.SubtitleLabel.setGeometry(QtCore.QRect(30, 30, 119, 28))
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.CardWidget_2 = CardWidget(pb)
        self.CardWidget_2.setGeometry(QtCore.QRect(150, 30, 421, 41))
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.StrongBodyLabel_3 = StrongBodyLabel(self.CardWidget_2)
        self.StrongBodyLabel_3.setGeometry(QtCore.QRect(20, 10, 271, 19))
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.CaptionLabel = CaptionLabel(pb)
        self.CaptionLabel.setGeometry(QtCore.QRect(10, 80, 131, 16))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.RadioButton = RadioButton(pb)
        self.RadioButton.setGeometry(QtCore.QRect(380, 440, 181, 24))
        self.RadioButton.setObjectName("RadioButton")
        self.PrimaryPushButton = PrimaryPushButton(pb)
        self.PrimaryPushButton.setGeometry(QtCore.QRect(610, 430, 153, 41))
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.PrimaryPushButton_2 = PrimaryPushButton(pb)
        self.PrimaryPushButton_2.setGeometry(QtCore.QRect(380, 90, 111, 31))
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.label = QtWidgets.QLabel(pb)
        self.label.setGeometry(QtCore.QRect(380, 130, 381, 281))
        self.label.setStyleSheet("border-image: url(:/img/resource/img2.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.HyperlinkButton = HyperlinkButton(pb)
        self.HyperlinkButton.setGeometry(QtCore.QRect(410, 330, 271, 51))
        self.HyperlinkButton.setObjectName("HyperlinkButton")

        self.retranslateUi(pb)
        QtCore.QMetaObject.connectSlotsByName(pb)

    def retranslateUi(self, pb):
        _translate = QtCore.QCoreApplication.translate
        pb.setWindowTitle(_translate("pb", "Form"))
        self.SubtitleLabel.setText(_translate("pb", "高级启动"))
        self.StrongBodyLabel_3.setText(_translate("pb", "配置文件请到MeFrp官网获取"))
        self.CaptionLabel.setText(_translate("pb", "配置文件请粘贴在此处"))
        self.RadioButton.setText(_translate("pb", "以其他系统的方式启动"))
        self.PrimaryPushButton.setText(_translate("pb", "启动服务"))
        self.PrimaryPushButton_2.setText(_translate("pb", "更新配置文件"))
        self.HyperlinkButton.setText(_translate("pb", "稳定运行, MeFrp\n"
"网站 - 『读书须用意，一字值千金。』"))
from qfluentwidgets import CaptionLabel, CardWidget, HyperlinkButton, PrimaryPushButton, RadioButton, StrongBodyLabel, SubtitleLabel, TextEdit
import rc_rc
